# Generated by Django 4.0.1 on 2022-01-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('heading', models.CharField(default='', max_length=500)),
                ('sub_heading', models.CharField(default='', max_length=500)),
                ('sub_title', models.CharField(default='', max_length=500)),
                ('content', models.CharField(max_length=300)),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
