# Generated by Django 4.0.1 on 2022-01-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='content',
            new_name='headingContent',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='sub_heading',
            new_name='subHeading',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='subHeadingContent',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='titleContent',
            field=models.CharField(default='', max_length=300),
        ),
    ]
