# Generated by Django 3.2.6 on 2021-12-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=5000)),
                ('First_name', models.CharField(max_length=90)),
                ('Last_name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=110)),
                ('Address', models.CharField(max_length=1000)),
                ('Address_2', models.CharField(max_length=1000)),
                ('Country', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Zip', models.CharField(max_length=15)),
            ],
        ),
    ]
