# Generated by Django 3.2.6 on 2021-12-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211230_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='Address_2',
        ),
    ]
