# Generated by Django 3.2.6 on 2022-01-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_statusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='update_desc',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
