# Generated by Django 4.0.1 on 2022-01-21 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_statusupdate_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='Zip',
            new_name='zip_code',
        ),
    ]
